export enum RouteNames {
  HOME = 'Home',
  LOGIN = 'Login',
  LOGOUT = 'Logout',
  PROFILE = 'Profile',

  ACTUAL_PRODUCTS_LIST = 'actualProductList',
  ACTUAL_PRODUCTS_ADD = 'actualProductAdd',
  ACTUAL_PRODUCTS_EDIT = 'actualProductEdit',
  BRAND_LIST = 'brandList',
  BRAND_ADD = 'brandAdd',
  BRAND_EDIT = 'brandEdit',
  PRODUCT_LIST = 'productList',
  PRODUCT_ADD = 'productAdd',
  PRODUCT_EDIT = 'productEdit',
  PRODUCT_TYPE_LIST = 'productTypeList',
  PRODUCT_TYPE_ADD = 'productTypeAdd',
  PRODUCT_TYPE_EDIT = 'productTypeEdit',
  VARIANT_LIST = 'variantList',
  VARIANT_ADD = 'variantAdd',
  VARIANT_EDIT = 'variantEdit',
  VARIANT_BULK_CREATE = 'variantBulkCreate',
  EDIT_VARIANT_STATUS = 'editVariantStatus',
  EDIT_VARIANT_STATUS_DKPC = 'editVariantStatusDKPC',
  DK_CREDENTIALS = 'digiCredentials',
  SCRAPE_INVOICE = 'scrapeInvoice',
  INACTIVE_VARIANTS = 'inactiveVariants',
  TOGGLE_VARIANT_STATUS = 'toggleVariantStatus',

  CONTACT_LIST = 'ContactList',

  INVOICE_LIST = 'invoiceList',
  INVOICE_DETAILS = 'invoiceDetails',
  COST_LIST = 'costList',
  COST_ADD = 'costAdd',
  COST_EDIT = 'costEdit',
  COST_TYPE_LIST = 'costTypeList',
  COST_TYPE_ADD = 'costTypeAdd',
  COST_TYPE_EDIT = 'costTypeEdit',
  INCOME_LIST = 'incomeList',
  INCOME_ADD = 'incomeAdd',
  INCOME_EDIT = 'incomeEdit',
  PRODUCT_COST_LIST = 'productCostList',
  PRODUCT_COST_ADD = 'productCostAdd',
  PRODUCT_COST_EDIT = 'productCostEdit',
  TEST_PAGE = 'testPage',
  PROFIT_BY_DATE = 'profitByDate',
  PROFIT_ALL_YEAR = 'profitAllYear',
  SALES_COUNT = 'salesCount',

  JUST_RAIN = 'justRain',
  ERROR_404 = 'error_404',
}


export default RouteNames
