export const urls = {
  token: 'token/',
  refreshToken: 'token/refresh/',
  userProfile: 'users/profile/',
  users: 'users/users/',
  userOwnInfo: 'users/users/my-info/',
  changePassword: 'auth/users/{user_id}/change-password/',

  authGroups: 'users/auth-groups/',
  authPermissions: 'users/auth-permissions/',

  callLocal:'admin/auth/call-local/',

  brands: 'products/brands/',
  actualProducts: 'products/actual-products/',
  actualProductsRelatedSelectors: 'products/actual-products/{0}/related-selectors/',
  variantDigiData: 'products/variant-digi-data/',
  variantDigiDataDKPC: 'products/variant-digi-data-dkpc/',
  products: 'products/products/',
  productTypes: 'products/products-types/',
  variantSelectorTypes: 'products/variant-selector-types/',
  variantSelectors: 'products/variant-selectors/',
  variants: 'products/variants/',
  variantBulkCreate: 'products/variants/bulk-create/',
  toggleVariantStatus: 'products/variants/toggle-status/',
  brandsAll: 'products/brands-all/',
  actualProductByBrand: 'products/actual-product-by-brand/{0}/',
  inactiveVariants: 'products/inactive-variants/',

  robotStatus: 'products/robot-status/',
  updateVariantData: 'products/update-variant-data/',
  invoiceExcel: 'products/invoice-excel/',
  digiCreds: 'products/digi-creds/',
  celeryTest: 'products/celery-task-test/',
  scrapeInvoice: 'products/scrape-invoice-page/',
  taskState: 'products/task-state/{0}/',
  taskTestSuccess: 'products/task-test-success/',
  taskTestFail: 'products/task-test-fail/',

  costs: 'accounting/costs/',
  costTypes: 'accounting/cost-types/',
  incomes: 'accounting/incomes/',
  productCosts: 'accounting/product-costs/',
  profit: 'accounting/profit/',
  profitYear: 'accounting/profit-year/',
  invoices: 'accounting/invoices/',
  invoiceItems: 'accounting/invoice-items/',
  invoiceActualItems: 'accounting/invoice-actual-items/',
  salesCount: 'accounting/sales-count/',

  robotCarList:'car-robot/cars/',
  robotCarDetail:'car-robot/cars/{0}/',
}

export default urls
